site_name: Extreme Rainfall Monitoring
site_description: Extreme rainfall monitoring, will it trigger a flood?
site_url: "https://wfpidn.github.io/ERM"
repo_url: https://github.com/wfpidn/ERM
repo_name: wfpidn/ERM


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    logo: material/library
    favicon: assets/images/favicon.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate

plugins:
  - search:
      separator: '[\s\-\.]+'

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - admonition
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      clickable_checkbox: false
      custom_checkbox: true
  - def_list


nav:
    - About: index.md
    - Revision History: history.md
    - Overview: 
        - Hydrometeorological Disasters: o-hd.md
        - Remote Sensing Precipitation: o-rsp.md
        - Data: o-data.md
    - Methodology: 
        - Developing event-identification threshold: m-eit.md
        - Find areas at risk of flooding: m-rof.md
        - Evaluating alert quality: m-eaq.md
        - Novelty, limitation and constraint: m-nlc.md
    - How-to?: 
        - Pre-downloaded and processed data: ht-pre.md
        - Acquire IMERG data: ht-imerg.md
        - Acquire GEFS data: ht-gefs.md
        - Extreme rainfall calculation: ht-erc.md
    - Implementation:
        - Google Earth Engine: i-gee.md
        - Demo: i-demo.md